version: "3"

services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", '''db.adminCommand("ping")''']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mongo-seed:
    build:
      context: .
      dockerfile: docker/mongo-seed/Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./scripts:/app/scripts
      - ./german_credit_data.xls:/app/german_credit_data.xls:ro
    environment:
      - MONGO_URI=mongodb://mongodb:27017/german_credit
      - DATASET_PATH=/app/german_credit_data.xls

  jupyterlab:
    build:
      context: .
      dockerfile: docker/jupyterlab/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/german_credit
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token=''

volumes:
  mongo-data:
